spring:
  profiles:
    group:
      "local": "testdb,common"

---
spring:
  profiles:
    group:
      "dev":  "testdb,common"
---
spring:
  profiles:
    group:
      "prod": "proddb,common"


---
##local, dev
spring:
  datasource:
    username: sa
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
  config:
    activate:
      on-profile: "testdb"
logging:
  level:
    tacos: DEBUG
---
## prod
spring:
  datasource:
    url: jdbc:mysql://localhost/tacocloud
    username: tacouser
    password: tacopassword
  config:
    activate:
      on-profile: "proddb"
logging:
  level:
    tacos : WARN

---
## 공통 속성
spring:
  config:
    activate:
      on-profile: "common"
  thymeleaf:
    cache: false
  artemis:
    broker-url: artemis.tacocloud.com:61617
    user: tacoweb
    password: l3tm31n
  jms:
    template:
      default-destination: tacocloud.order.queue
